# Generated by Django 5.0.6 on 2024-05-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal', models.CharField(default='Hubli', max_length=400)),
                ('number_plate', models.CharField(default='Hubli', max_length=400)),
                ('extracted_data', models.CharField(default='Hubli', max_length=400)),
                ('entered_timing', models.CharField(default='Hubli', max_length=400)),
                ('status', models.CharField(default='Active', max_length=400)),
            ],
        ),
    ]
