# Generated by Django 5.0.6 on 2024-05-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Hubli', max_length=400)),
                ('car_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='Active', max_length=400)),
                ('extracted_data', models.CharField(default='Hubli', max_length=400)),
                ('number_plate', models.CharField(max_length=15)),
                ('entered_timings', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CarDetails',
        ),
    ]
