# Generated by Django 5.0.6 on 2024-05-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_car_delete_cardetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='img', upload_to='car_images/'),
        ),
    ]
