# Generated by Django 5.0.6 on 2024-05-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_car_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Hubli', max_length=400)),
                ('number_plate', models.CharField(max_length=15)),
                ('entered_timings', models.CharField(max_length=15)),
                ('entered_timings1', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
